package com.rajeev.awsprodinvent.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Products")
public class Product {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String code;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private int quantity;
    @DynamoDBAttribute
    private String availableDC;
}